"""
Từ điển Teencode, Viết tắt, Lóng và Lỗi chính tả tiếng Việt phổ biến trong Đánh giá / Bình luận.
"""

TEENCODE_DICT = {
    # Phủ định
    "ko": "không",
    "k": "không",
    "kh": "không",
    "khong": "không",
    "khôg": "không",
    "khg": "không",
    "hok": "không",
    "hong": "không",
    "hổng": "không",
    "hem": "không",
    "k0": "không",
    "kg": "không",
    "hông": "không",
    "k bit": "không biết",
    "k rõ": "không rõ",

    # Trợ từ, động từ, đại từ
    "dc": "được",
    "đc": "được",
    "dk": "được",
    "đk": "được",
    "duc": "được",
    "đuc": "được",
    "nv": "nhân viên",
    "nvien": "nhân viên",
    "nhanvien": "nhân viên",
    "sp": "sản phẩm",
    "spham": "sản phẩm",
    "sanpham": "sản phẩm",
    "s/p": "sản phẩm",
    "mk": "mình",
    "mik": "mình",
    "m": "mình",
    "mn": "mọi người",
    "mng": "mọi người",
    "ng": "người",
    "ngta": "người ta",
    "cx": "cũng",
    "cung": "cũng",
    "vs": "với",
    "zới": "với",
    "z": "vậy",
    "zay": "vậy",
    "zậy": "vậy",
    "vay": "vậy",
    "thui": "thôi",
    "nha": "nha",
    "nhe": "nhé",
    "nè": "nè",
    "nèe": "nè",
    "ak": "à",
    "ah": "à",
    "uh": "ừ",
    "uhm": "ừm",
    "uk": "ừ",
    "um": "ừm",
    "đug": "đúng",
    "đúg": "đúng",
    "chug": "chung",
    "chúg": "chúng",

    # Cảm thán & Tính từ
    "tuỵt": "tuyệt",
    "tuyt": "tuyệt",
    "tuyệt zời": "tuyệt vời",
    "tuyet voi": "tuyệt vời",
    "tuyệt vời": "tuyệt vời",
    "tuyệt cú mèo": "tuyệt vời",
    "supercalifragilisticexpialidocious": "siêu ngon tuyệt vời",
    "qá": "quá",
    "wa": "quá",
    "wá": "quá",
    "qua": "quá",
    "dth": "dễ thương",
    "dễ thw": "dễ thương",
    "dễ thg": "dễ thương",
    "cute": "dễ thương",
    "oke": "tốt",
    "ok": "tốt",
    "oki": "tốt",
    "okee": "tốt",
    "okela": "tốt",
    "okey": "tốt",
    "gút": "tốt",
    "gut": "tốt",
    "good": "tốt",
    "nice": "tốt",
    "best": "tốt nhất",
    "bt": "bình thường",
    "bth": "bình thường",
    "bthg": "bình thường",
    "tệ hại": "tệ",
    "kém": "kém",
    "dỏm": "dở",
    "đểu": "giả dối",
    "fake": "hàng giả",
    "pha-ke": "hàng giả",

    # Liên lạc, mạng xã hội, giao dịch
    "shop": "shop",
    "shopp": "shop",
    "sop": "shop",
    "sọp": "shop",
    "fb": "facebook",
    "ib": "nhắn tin",
    "inb": "nhắn tin",
    "inbox": "nhắn tin",
    "rep": "trả lời",
    "tl": "trả lời",
    "tloi": "trả lời",
    "dt": "điện thoại",
    "đt": "điện thoại",
    "sdt": "số điện thoại",
    "stk": "số tài khoản",
    "ck": "chuyển khoản",
    "ship": "giao hàng",
    "shipper": "người giao hàng",
    "order": "đặt hàng",
    "sz": "kích cỡ",
    "size": "kích cỡ",
    "màu": "màu",
    "min": "phút",
    "sec": "giây",
    "k": "nghìn",
    "tr": "triệu",
    "vnd": "đồng",
    "tks": "cảm ơn",
    "thanks": "cảm ơn",
    "thank": "cảm ơn",
    "thx": "cảm ơn",
    "cam on": "cảm ơn",
    "cmon": "cảm ơn",
    "ty": "cảm ơn",

    # Cụm từ và tiếng Anh thông dụng
    "l9cation": "vị trí",
    "location": "vị trí",
    "l0cation": "vị trí",
    "localtion": "vị trí",
    "loaction": "vị trí",
    "absolutely amazing": "hoàn toàn tuyệt vời",
    "i like macdonald": "tôi thích macdonald",
    "i like mcdonald": "tôi thích mcdonald",
    "i like mcdonalds": "tôi thích mcdonald",
    "i like mcdonald's": "tôi thích mcdonald",
    "all good": "tất cả đều tốt",
    "cool": "tuyệt",
    "good": "tốt",
    "goodd": "tốt",
    "gooddd": "tốt",
    "goodddd": "tốt",
    "gooddddd": "tốt",
    "goodddddd": "tốt",
    "supercalifragilisticexpialidocious": "siêu ngon tuyệt vời",
    "tắt mm app đi": "",
    "tắt app": "",
    "tải app": "",
    "mở app": "",

    # Từ địa phương, lỗi gõ phím
    "hoang mang": "hoang mang",
    "ung ho": "ủng hộ",
    "ung ho shop": "ủng hộ shop",
    "chat luong": "chất lượng",
    "giao hang": "giao hàng",
    "dong goi": "đóng gói",
    "chinh hang": "chính hãng",
    "hai long": "hài lòng",
    "nhiet tinh": "nhiệt tình",
    "than thien": "thân thiện"
}

LEETSPEAK_MAP = {
    '0': 'o',
    '1': 'i',
    '3': 'e',
    '4': 'a',
    '5': 's',
    '7': 't',
    '8': 'b',
    '9': 'o',
}
